[profile.release]
panic = 'unwind'

[workspace]
members = [
	'nodes/parachain',
	'nodes/standalone',
	'pallets/credential',
	'pallets/post',
	'pallets/token',
	'runtimes/parachain',
	'runtimes/standalone',
]