apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" . }}
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.node.p2pPort }}
      targetPort: p2p
      nodePort: {{ .Values.service.nodePortP2P }}
      protocol: TCP
      name: p2p
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.createP2P }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.p2pService" . }}
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.node.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.httpRpcService" . }}
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.node.httpRpcPort }}
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}
