version: "3"

services:
  node:
    build:
      context: .
    image: myriad/node:latest
    volumes:
      - data:/data
    command: >
      --base-path /data
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944

volumes:
  data:
